apiVersion: v1
kind: Secret
metadata:
  name: store-secrets
  namespace: store-app
type: Opaque
data:
  SECRET_KEY: <!-- Base64 encoded secret key here -->
  AFRICAS_TALKING_API_KEY: <!-- Base64 encoded API key here -->
  AFRICAS_TALKING_USERNAME: <!-- Base64 encoded username here -->
  AFRICAS_TALKING_SENDER_ID: <!-- Base64 encoded sender ID here -->
  EMAIL_HOST_PASSWORD: <!-- Base64 encoded email host password here -->
  EMAIL_HOST_USER: <!-- Base64 encoded email host user here -->
  DB_PASSWORD: <!-- Base64 encoded database password here -->
  DB_USER:  <!-- Base64 encoded database user here -->
  GOOGLE_OAUTH2_CLIENT_ID: <!-- Base64 encoded Google OAuth2 client ID here -->
  GOOGLE_OAUTH2_CLIENT_SECRET: <!-- Base64 encoded Google OAuth2 client secret here -->


---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: store-app
type: Opaque
data:
  POSTGRES_USER: <!-- Base64 encoded database user here -->
  POSTGRES_PASSWORD: <!-- Base64 encoded database password here -->

